version: 1.0.{build}
branches:
  only:
  - master
image:
- Visual Studio 2015
- Visual Studio 2017
init:
- git config --global core.autocrlf true
configuration:
- Debug
- Release
environment:
  matrix:
    - image_flag: 2015
    - image_flag: 2017
matrix:
  exclude:
    - image: Visual Studio 2015
      image_flag: 2017
    - image: Visual Studio 2017
      image_flag: 2015
before_build:
- nuget restore
build:
  project: PerfView.sln
  verbosity: minimal
test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\perfview\src\LinuxEvent.Tests\bin\%configuration%\LinuxTracing.Tests.exe -noshadow -appveyor" -threshold:1 -oldStyle -returntargetcode -filter:"+[*]* -[Xunit*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -output:.\PerfView_coverage.xml
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\perfview\src\TraceEvent\Ctf\CtfTracing.Tests\bin\%configuration%\Tests.dll -noshadow -appveyor" -threshold:1 -oldStyle -returntargetcode -filter:"+[*]* -[Xunit*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -mergebyhash -mergeoutput -output:.\PerfView_coverage.xml
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\perfview\src\TraceEvent\TraceEvent.Tests\bin\%configuration%\TraceEventTests.dll -noshadow -appveyor" -threshold:1 -oldStyle -returntargetcode -filter:"+[*]* -[Xunit*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -mergebyhash -mergeoutput -output:.\PerfView_coverage.xml
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\perfview\src\PerfView.Tests\bin\%configuration%\PerfViewTests.dll -noshadow -appveyor" -threshold:1 -oldStyle -returntargetcode -filter:"+[*]* -[Xunit*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -mergebyhash -mergeoutput -output:.\PerfView_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -n "VS%image_flag% %configuration%" -f "PerfView_coverage.xml" -F "%image_flag%,%configuration%"
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
artifacts:
- path: 'src\PerfView\bin\$(configuration)\PerfView.exe'
- path: 'src\PerfView64\bin\$(configuration)\PerfView64.exe'
- path: 'src\TraceEvent\bin\$(configuration)\*.nupkg'
